\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 3: Physical Properties of Rivers},
            pdfauthor={Felipe Raby Amadori},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 3: Physical Properties of Rivers}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Felipe Raby Amadori}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Hydrologic Data Analysis on the
physical properties of rivers.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Salk\_A03\_RiversPhysical.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on 18 September 2019 at 9:00 am.

\hypertarget{setup}{%
\subsection{Setup}\label{setup}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Verify your working directory is set to the R project file,
\item
  Load the tidyverse, dataRetrieval, and cowplot packages
\item
  Set your ggplot theme (can be theme\_classic or something else)
\item
  Import a data frame called ``MysterySiteDischarge'' from USGS gage
  site 03431700. Upload all discharge data for the entire period of
  record. Rename columns 4 and 5 as ``Discharge'' and ``Approval.Code''.
  DO NOT LOOK UP WHERE THIS SITE IS LOCATED.
\item
  Build a ggplot of discharge over the entire period of record.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{message =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{warning =} \OtherTok{FALSE}\NormalTok{)}

\CommentTok{#Verify your working directory is set to the R project file}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "C:/Users/Felipe/OneDrive - Duke University/1. DUKE/Ramos 3 Semestre/Hydrologic_Data_Analysis"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Load the tidyverse, dataRetrieval, and cowplot packages}
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ----------------------------------- tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.2.1     v purrr   0.3.2
## v tibble  2.1.3     v dplyr   0.8.3
## v tidyr   0.8.3     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.4.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts -------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(cowplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ********************************************************
\end{verbatim}

\begin{verbatim}
## Note: As of version 1.0.0, cowplot does not change the
\end{verbatim}

\begin{verbatim}
##   default ggplot2 theme anymore. To recover the previous
\end{verbatim}

\begin{verbatim}
##   behavior, execute:
##   theme_set(theme_cowplot())
\end{verbatim}

\begin{verbatim}
## ********************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(dataRetrieval)}
\KeywordTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:cowplot':
## 
##     stamp
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:base':
## 
##     date
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Set your ggplot theme (can be theme_classic or something else)}
\NormalTok{felipe_theme <-}\StringTok{ }\KeywordTok{theme_light}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{12}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"grey8"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"right"}\NormalTok{, }\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }
\KeywordTok{theme_set}\NormalTok{(felipe_theme)}

\CommentTok{#Import a data frame called "MysterySiteDischarge" from USGS gage site 03431700.}
\CommentTok{#Upload all discharge data for the entire period of record. Rename columns 4 and}
\CommentTok{#5 as "Discharge" and "Approval.Code".}

\NormalTok{MysterySiteDischarge <-}\StringTok{ }\KeywordTok{readNWISdv}\NormalTok{(}\DataTypeTok{siteNumbers =} \StringTok{"03431700"}\NormalTok{,}
                     \DataTypeTok{parameterCd =} \StringTok{"00060"}\NormalTok{, }\CommentTok{# discharge (ft3/s)}
                     \DataTypeTok{startDate =} \StringTok{""}\NormalTok{,}
                     \DataTypeTok{endDate =} \StringTok{""}\NormalTok{)}

\KeywordTok{names}\NormalTok{(MysterySiteDischarge)[}\DecValTok{4}\OperatorTok{:}\DecValTok{5}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Discharge"}\NormalTok{, }\StringTok{"Approval.Code"}\NormalTok{)}

\CommentTok{#Checking for missing data}
\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(MysterySiteDischarge}\OperatorTok{$}\NormalTok{Discharge))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(MysterySiteDischarge)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   agency_cd           site_no               Date           
##  Length:19127       Length:19127       Min.   :1964-08-01  
##  Class :character   Class :character   1st Qu.:1977-09-03  
##  Mode  :character   Mode  :character   Median :1990-10-30  
##                                        Mean   :1992-02-21  
##                                        3rd Qu.:2006-08-13  
##                                        Max.   :2019-09-17  
##    Discharge       Approval.Code     
##  Min.   :   0.05   Length:19127      
##  1st Qu.:   4.70   Class :character  
##  Median :  13.00   Mode  :character  
##  Mean   :  35.28                     
##  3rd Qu.:  32.40                     
##  Max.   :7020.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Build a ggplot of discharge over the entire period of record.}

\NormalTok{MisteryPlot <-}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(MysterySiteDischarge, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Date, }\DataTypeTok{y =}\NormalTok{ Discharge)) }\OperatorTok{+}
\StringTok{         }\KeywordTok{geom_line}\NormalTok{() }\OperatorTok{+}
\StringTok{         }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Year"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(}\StringTok{"Discharge (ft"}\OperatorTok{^}\DecValTok{3}\OperatorTok{*}\StringTok{"/s)"}\NormalTok{))}
  \KeywordTok{print}\NormalTok{(MisteryPlot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_Raby_RiversPhysical_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Build a ggplot of discharge over the entire period of record using}
\CommentTok{#geom_point to look for missing data.}

\NormalTok{MisteryPlot <-}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(MysterySiteDischarge, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Date, }\DataTypeTok{y =}\NormalTok{ Discharge)) }\OperatorTok{+}
\StringTok{         }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{color =} \StringTok{"red"}\NormalTok{, }\DataTypeTok{size =} \FloatTok{0.5}\NormalTok{) }\OperatorTok{+}
\StringTok{         }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Year"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(}\StringTok{"Discharge (ft"}\OperatorTok{^}\DecValTok{3}\OperatorTok{*}\StringTok{"/s)"}\NormalTok{))}
\KeywordTok{print}\NormalTok{(MisteryPlot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_Raby_RiversPhysical_files/figure-latex/unnamed-chunk-1-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#There is a period of approx. 2 years and 7 months with no data between}
\CommentTok{#1990-12-16 and 1993-08-01}
\end{Highlighting}
\end{Shaded}

\hypertarget{analyze-seasonal-patterns-in-discharge}{%
\subsection{Analyze seasonal patterns in
discharge}\label{analyze-seasonal-patterns-in-discharge}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Add a ``Year'' and ``Day.of.Year'' column to the data frame.
\item
  Create a new data frame called ``MysterySiteDischarge.Pattern'' that
  has columns for Day.of.Year, median discharge for a given day of year,
  75th percentile discharge for a given day of year, and 25th percentile
  discharge for a given day of year. Hint: the summarise function
  includes \texttt{quantile}, wherein you must specify \texttt{probs} as
  a value between 0 and 1.
\item
  Create a plot of median, 75th quantile, and 25th quantile discharges
  against day of year. Median should be black, other lines should be
  gray.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Add a "Year" and "Day.of.Year" column to the data frame.}
\NormalTok{MysterySiteDischarge <-}\StringTok{ }
\StringTok{  }\NormalTok{MysterySiteDischarge }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Year =} \KeywordTok{year}\NormalTok{(Date)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Day.of.Year =} \KeywordTok{yday}\NormalTok{(Date))}

\CommentTok{#Create a new data frame called "MysterySiteDischarge.Pattern" that has columns}
\CommentTok{#for Day.of.Year, median discharge for a given day of year, 75th percentile}
\CommentTok{#discharge for a given day of year, and 25th percentile discharge for a given}
\CommentTok{#day of year.}

\NormalTok{MysterySiteDischarge.Pattern <-}\StringTok{ }
\StringTok{  }\NormalTok{MysterySiteDischarge }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Day.of.Year) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{MedianDischarge =} \KeywordTok{quantile}\NormalTok{(Discharge, }\DataTypeTok{probs=}\FloatTok{0.5}\NormalTok{),}
            \DataTypeTok{Percent75Discharge =} \KeywordTok{quantile}\NormalTok{(Discharge, }\DataTypeTok{probs=}\FloatTok{0.75}\NormalTok{),}
            \DataTypeTok{Percent25Discharge =} \KeywordTok{quantile}\NormalTok{(Discharge, }\DataTypeTok{probs=}\FloatTok{0.25}\NormalTok{))}
  
\CommentTok{#Create a plot of median, 75th quantile, and 25th quantile discharges against}
\CommentTok{#day of year. Median should be black, other lines should be gray. }

\NormalTok{MysterySiteDischargePatternPlot <-}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(MysterySiteDischarge.Pattern, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Day.of.Year)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ MedianDischarge)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ Percent75Discharge), }\DataTypeTok{color =} \StringTok{"gray"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ Percent25Discharge), }\DataTypeTok{color =} \StringTok{"gray"}\NormalTok{) }\OperatorTok{+}\StringTok{  }
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"Day of Year"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(}\StringTok{"Discharge (ft"}\OperatorTok{^}\DecValTok{3}\OperatorTok{*}\StringTok{"/s)"}\NormalTok{)) }
\KeywordTok{print}\NormalTok{(MysterySiteDischargePatternPlot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_Raby_RiversPhysical_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  What seasonal patterns do you see? What does this tell you about
  precipitation patterns and climate in the watershed?
\end{enumerate}

\begin{quote}
The period of lower discharge values is approx. between day \#150 and
day \#300 which corresponds to the end of Spring and the Summer season.
Discharge values start to increase importantly during the Fall season
(probably due to seasonal rains). Discharge values stay at their highest
levels during the whole winter and start to decline towards the
beginning of Spring. Mystery Site probably is located in a place with
low spring/summer and high fall/winter precipitations. There is no clear
sign of an increase of flow when temperatures start to increase (Spring)
meaning that there is probably no snow pack melting going to Mystery
Site.
\end{quote}

\hypertarget{create-and-analyze-recurrence-intervals}{%
\subsection{Create and analyze recurrence
intervals}\label{create-and-analyze-recurrence-intervals}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\item
  Create two separate data frames for MysterySite.Annual.30yr (first 30
  years of record) and MysterySite.Annual.Full (all years of record).
  Use a pipe to create your new data frame(s) that includes the year,
  the peak discharge observed in that year, a ranking of peak
  discharges, the recurrence interval, and the exceedende probability.
\item
  Create a plot that displays the discharge vs.~recurrence interval
  relationship for the two separate data frames (one set of points
  includes the values computed from the first 30 years of the record and
  the other set of points includes the values computed for all years of
  the record.
\item
  Create a model to predict the discharge for a 100-year flood for both
  sets of recurrence intervals.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Create two separate data frames for MysterySite.Annual.30yr (first 30 years of}
\CommentTok{#record) and MysterySite.Annual.Full (all years of record). Use a pipe to create}
\CommentTok{#your new data frame(s) that includes the year, the peak discharge observed in}
\CommentTok{#that year, a ranking of peak discharges, the recurrence interval, and the}
\CommentTok{#exceedende probability.}

\NormalTok{MysterySite.Annual}\FloatTok{.30}\NormalTok{yr <-}\StringTok{ }
\StringTok{  }\NormalTok{MysterySiteDischarge }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(Year }\OperatorTok{<}\StringTok{ }\DecValTok{1996}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Year) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{PeakDischarge =} \KeywordTok{max}\NormalTok{(Discharge)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Rank =} \KeywordTok{rank}\NormalTok{(}\OperatorTok{-}\NormalTok{PeakDischarge),}
         \DataTypeTok{RecurrenceInterval =}\NormalTok{ (}\KeywordTok{length}\NormalTok{(Year) }\OperatorTok{+}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{/}\NormalTok{Rank, }
         \DataTypeTok{Probability =} \DecValTok{1}\OperatorTok{/}\NormalTok{RecurrenceInterval, }\DataTypeTok{DataSet =} \StringTok{"First 30y Data"}\NormalTok{)}

\NormalTok{MysterySite.Annual.Full <-}\StringTok{ }
\StringTok{  }\NormalTok{MysterySiteDischarge }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Year) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{PeakDischarge =} \KeywordTok{max}\NormalTok{(Discharge)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Rank =} \KeywordTok{rank}\NormalTok{(}\OperatorTok{-}\NormalTok{PeakDischarge),}
         \DataTypeTok{RecurrenceInterval =}\NormalTok{ (}\KeywordTok{length}\NormalTok{(Year) }\OperatorTok{+}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{/}\NormalTok{Rank, }
         \DataTypeTok{Probability =} \DecValTok{1}\OperatorTok{/}\NormalTok{RecurrenceInterval, }\DataTypeTok{DataSet =} \StringTok{"Full Data"}\NormalTok{)}


\CommentTok{#Analize incomplete years}

\CommentTok{#Create a plot that displays the discharge vs. recurrence interval relationship}
\CommentTok{#for the two separate data frames (one set of points includes the values}
\CommentTok{#computed from the first 30 years of the record and the other set of points}
\CommentTok{#includes the values computed for all years of the record.}

\NormalTok{MisterySite.Annual.Both <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(MysterySite.Annual.Full, MysterySite.Annual}\FloatTok{.30}\NormalTok{yr)}

\NormalTok{MysterySiteRecurrencePlot.Both <-}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(MisterySite.Annual.Both, }
         \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ RecurrenceInterval, }\DataTypeTok{y =}\NormalTok{ PeakDischarge, }\DataTypeTok{color =}\NormalTok{ DataSet)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_color_brewer}\NormalTok{(}\DataTypeTok{palette =} \StringTok{"Set1"}\NormalTok{) }
\KeywordTok{print}\NormalTok{(MysterySiteRecurrencePlot.Both)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_Raby_RiversPhysical_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Create a model to predict the discharge for a 100-year flood for both sets of}
\CommentTok{#recurrence intervals. }

\CommentTok{#30year}
\NormalTok{MysterySite.Annual}\FloatTok{.30}\NormalTok{yr.Model <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ MysterySite.Annual}\FloatTok{.30}\NormalTok{yr,}
\NormalTok{                                    PeakDischarge }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(RecurrenceInterval))}
\KeywordTok{summary}\NormalTok{(MysterySite.Annual}\FloatTok{.30}\NormalTok{yr.Model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = PeakDischarge ~ log(RecurrenceInterval), data = MysterySite.Annual.30yr)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -974.12 -337.65   34.84  232.57 2908.00 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(>|t|)    
## (Intercept)               -69.87     185.73  -0.376     0.71    
## log(RecurrenceInterval)  1217.79     147.16   8.275 5.26e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 673.9 on 28 degrees of freedom
## Multiple R-squared:  0.7098, Adjusted R-squared:  0.6994 
## F-statistic: 68.48 on 1 and 28 DF,  p-value: 5.261e-09
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MysterySite.Annual}\FloatTok{.30}\NormalTok{yr.Model}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{] }\OperatorTok{+}
\StringTok{  }\NormalTok{MysterySite.Annual}\FloatTok{.30}\NormalTok{yr.Model}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\KeywordTok{log}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept) 
##    5538.257
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Full Record}
\NormalTok{MysterySite.Annual.Full.Model <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ MysterySite.Annual.Full,}
\NormalTok{                                    PeakDischarge }\OperatorTok{~}\StringTok{ }\KeywordTok{log}\NormalTok{(RecurrenceInterval))}
\KeywordTok{summary}\NormalTok{(MysterySite.Annual.Full.Model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = PeakDischarge ~ log(RecurrenceInterval), data = MysterySite.Annual.Full)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -955.95 -236.29   41.91  210.67 2805.35 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(>|t|)    
## (Intercept)               -2.001    116.322  -0.017    0.986    
## log(RecurrenceInterval) 1052.234     88.834  11.845   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 578.3 on 52 degrees of freedom
## Multiple R-squared:  0.7296, Adjusted R-squared:  0.7244 
## F-statistic: 140.3 on 1 and 52 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MysterySite.Annual.Full.Model}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{] }\OperatorTok{+}
\StringTok{  }\NormalTok{MysterySite.Annual.Full.Model}\OperatorTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\KeywordTok{log}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept) 
##    4843.717
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  How did the recurrence interval plots and predictions of a 100-year
  flood differ among the two data frames? What does this tell you about
  the stationarity of discharge in this river?
\end{enumerate}

\begin{quote}
Looking at the recurrence interval plots, it can be seen that below 1000
ft3/s the curves are very similar. Above that value, data differs,
having the data of the first 30 years on record (30yearmodel) higher
peak discharge values for the same recurrence interval than the full
data (fullmodel). More over, for the prediction of the discharge for a
100-year flood for the 30yearmodel we got a discharge value of 5538.257
ft3/s and for the prediction of the discharge for a 100-year flood for
the fullmodel we got a discharge value of 4843.717 ft3/s which is
approx. a 13\% decrease. That difference between predictions is relevant
considering that those values could be use for designing flood
protection infrastructure or other type of important water
infrastructure. This tells me that the assumption of stationary flow
regimes in Mystery River is not perfectly correct. Recurrence values
vary importantly depending on the data selected to do the calculations
specially in data sets that include extreme outliers and periods of
missing data.
\end{quote}

\hypertarget{reflection}{%
\subsection{Reflection}\label{reflection}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  What are 2-3 conclusions or summary points about river discharge you
  learned through your analysis?
\end{enumerate}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  River discharge is highly seasonal. It can be learned a lot about the
  climate of a site by just looking at the discharge information.
\item
  Predicting the recurrence of discharge values in rivers is essential
  for infrastructure design. However, non-stationary discharge regimes
  can alter this calculations importantly. A designer or decision maker
  has to know this facts when selecting the data used for calculations.
  Every piece of extra information that can be obtained in recurrence
  calculations should be used or at least considered when making
  decisions. If a more conservative or risky approach is followed
  depends on the nature of the study or the design that is been
  performed.
\end{enumerate}
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  What data, visualizations, and/or models supported your conclusions
  from 13?
\end{enumerate}

\begin{quote}
I supported conclusion \#1 with the plot of median, 75th quantile, and
25th quantile discharges against day of year and all the data that was
used in creating that plot. I supported conclusion \#2 with the plot
that displays the discharge vs.~recurrence interval relationship for the
two separate data frames and the model to predict the discharge for a
100-year flood for both sets of recurrence intervals.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Did hands-on data analysis impact your learning about discharge
  relative to a theory-based lesson? If so, how?
\end{enumerate}

\begin{quote}
It definitely impacted my learning. It allowed me to work with the data,
to try to solve problems that happen while doing it. Also using real
data for learning allows us to immediately gain experience working with
``real life'' data and understand the gaps between theory and practice.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{15}
\tightlist
\item
  How did the real-world data compare with your expectations from
  theory?
\end{enumerate}

\begin{quote}
Real world data is rarely ``perfect'' and I think that is one the most
important things that we need to learn how to deal with. Also important
is how relevant are certain assumptions that are accepted in some fields
that sometimes can lead to important mistakes. Expectations from theory
would be to observe perfect seasons, perfect stationary data, no missing
values, no calibration mistakes in sensors. I think it could be said
that those expectations will be met almost never.
\end{quote}


\end{document}
