\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=2.54cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Assignment 5: Water Quality in Lakes},
            pdfauthor={Felipe Raby Amadori},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Assignment 5: Water Quality in Lakes}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Felipe Raby Amadori}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Hydrologic Data Analysis on
water quality in lakes

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single pdf file.
\item
  After Knitting, submit the completed exercise (HTML file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``A05\_Salk.html'') prior to submission.
\end{enumerate}

The completed exercise is due on 2 October 2019 at 9:00 am.

\hypertarget{setup}{%
\subsection{Setup}\label{setup}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Verify your working directory is set to the R project file,
\item
  Load the tidyverse, lubridate, and LAGOSNE packages.
\item
  Set your ggplot theme (can be theme\_classic or something else)
\item
  Load the LAGOSdata database and the trophic state index csv file we
  created on 2019/09/27.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{message =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{warning =} \OtherTok{FALSE}\NormalTok{)}

\CommentTok{#Verify your working directory is set to the R project file}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "C:/Users/Felipe/OneDrive - Duke University/1. DUKE/Ramos 3 Semestre/Hydrologic_Data_Analysis"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ------------------------------------------ tidyverse 1.2.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.2.1     v purrr   0.3.2
## v tibble  2.1.3     v dplyr   0.8.3
## v tidyr   0.8.3     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.4.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts --------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(cowplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ********************************************************
\end{verbatim}

\begin{verbatim}
## Note: As of version 1.0.0, cowplot does not change the
\end{verbatim}

\begin{verbatim}
##   default ggplot2 theme anymore. To recover the previous
\end{verbatim}

\begin{verbatim}
##   behavior, execute:
##   theme_set(theme_cowplot())
\end{verbatim}

\begin{verbatim}
## ********************************************************
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(LAGOSNE)}
\KeywordTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:cowplot':
## 
##     stamp
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:base':
## 
##     date
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Set your ggplot theme (can be theme_classic or something else)}
\NormalTok{felipe_theme <-}\StringTok{ }\KeywordTok{theme_light}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{12}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"grey8"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"right"}\NormalTok{, }\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }
\KeywordTok{theme_set}\NormalTok{(felipe_theme)}


\CommentTok{#Load the LAGOSdata database and the trophic state index csv file we created on 2019/09/27.}
\KeywordTok{load}\NormalTok{(}\DataTypeTok{file =} \StringTok{"./Data/Raw/LAGOSdata.rda"}\NormalTok{)}
\NormalTok{LAGOStrophic <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Processed/LAGOStrophic.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{trophic-state-index}{%
\subsection{Trophic State Index}\label{trophic-state-index}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Similar to the trophic.class column we created in class (determined
  from TSI.chl values), create two additional columns in the data frame
  that determine trophic class from TSI.secchi and TSI.tp (call these
  trophic.class.secchi and trophic.class.tp).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOStrophicComplete <-}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(LAGOStrophic, }
         \DataTypeTok{trophic.class.secchi =} 
            \KeywordTok{ifelse}\NormalTok{(TSI.secchi }\OperatorTok{<}\StringTok{ }\DecValTok{40}\NormalTok{, }\StringTok{"Oligotrophic"}\NormalTok{, }
                   \KeywordTok{ifelse}\NormalTok{(TSI.secchi }\OperatorTok{<}\StringTok{ }\DecValTok{50}\NormalTok{, }\StringTok{"Mesotrophic"}\NormalTok{,}
                          \KeywordTok{ifelse}\NormalTok{(TSI.secchi }\OperatorTok{<}\StringTok{ }\DecValTok{70}\NormalTok{, }\StringTok{"Eutrophic"}\NormalTok{, }\StringTok{"Hypereutrophic"}\NormalTok{)))) }


\NormalTok{LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.secchi <-}\StringTok{ }
\StringTok{  }\KeywordTok{factor}\NormalTok{(LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.secchi,}
         \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Oligotrophic"}\NormalTok{, }\StringTok{"Mesotrophic"}\NormalTok{, }\StringTok{"Eutrophic"}\NormalTok{, }\StringTok{"Hypereutrophic"}\NormalTok{))}

\NormalTok{LAGOStrophicComplete <-}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(LAGOStrophicComplete, }
         \DataTypeTok{trophic.class.tp =} 
            \KeywordTok{ifelse}\NormalTok{(TSI.tp }\OperatorTok{<}\StringTok{ }\DecValTok{40}\NormalTok{, }\StringTok{"Oligotrophic"}\NormalTok{, }
                   \KeywordTok{ifelse}\NormalTok{(TSI.tp }\OperatorTok{<}\StringTok{ }\DecValTok{50}\NormalTok{, }\StringTok{"Mesotrophic"}\NormalTok{,}
                          \KeywordTok{ifelse}\NormalTok{(TSI.tp }\OperatorTok{<}\StringTok{ }\DecValTok{70}\NormalTok{, }\StringTok{"Eutrophic"}\NormalTok{, }\StringTok{"Hypereutrophic"}\NormalTok{)))) }

\NormalTok{LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.tp <-}\StringTok{ }
\StringTok{  }\KeywordTok{factor}\NormalTok{(LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.tp,}
         \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\StringTok{"Oligotrophic"}\NormalTok{, }\StringTok{"Mesotrophic"}\NormalTok{, }\StringTok{"Eutrophic"}\NormalTok{, }\StringTok{"Hypereutrophic"}\NormalTok{))}

\KeywordTok{head}\NormalTok{(LAGOStrophicComplete)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   lagoslakeid sampledate   chla  tp secchi    gnis_name lake_area_ha state
## 1      126841 1985-11-05   8.40 100 1.0000  Silver Lake     32.38997    NY
## 2        6456 2006-06-15   5.64  14 2.2098         <NA>    861.58209    IL
## 3        6469 2006-06-19  41.90  88 0.4572 Tampier Lake     48.97546    IL
## 4       81320 1985-11-07   1.40 100 0.5000         <NA>     11.05260    NY
## 5      122514 1988-06-23 133.20 700 0.4000   Evens Lake     11.24954    NY
## 6        6450 2006-08-23  12.30  14 0.9144         <NA>    110.85536    IL
##   state_name sampleyear samplemonth season TSI.chl TSI.secchi TSI.tp
## 1   New York       1985          11   Fall      60         60     71
## 2   Illinois       2006           6 Summer      57         49     42
## 3   Illinois       2006           6 Summer      76         71     69
## 4   New York       1985          11   Fall      43         70     71
## 5   New York       1988           6 Summer      88         73     99
## 6   Illinois       2006           8 Summer      64         61     42
##    trophic.class trophic.class.secchi trophic.class.tp
## 1      Eutrophic            Eutrophic   Hypereutrophic
## 2      Eutrophic          Mesotrophic      Mesotrophic
## 3 Hypereutrophic       Hypereutrophic        Eutrophic
## 4    Mesotrophic       Hypereutrophic   Hypereutrophic
## 5 Hypereutrophic       Hypereutrophic   Hypereutrophic
## 6      Eutrophic            Eutrophic      Mesotrophic
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  How many observations fall into the four trophic state categories for
  the three metrics (trophic.class, trophic.class.secchi,
  trophic.class.tp)? Hint: \texttt{count} function.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Number of observations that fall into the four trophic state categories for trophic.class}
\CommentTok{#(using chlorophyll a concentration)}

\NormalTok{N_Obs_TrophicClass_Chl <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{summary}\NormalTok{(LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class))}
\KeywordTok{names}\NormalTok{(N_Obs_TrophicClass_Chl)[}\DecValTok{1}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Number_Observations"}\NormalTok{)}
\NormalTok{N_Obs_TrophicClass_Chl <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{TrophicState =} \KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_Chl),}
\NormalTok{                                     N_Obs_TrophicClass_Chl)}
\KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_Chl) <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\NormalTok{N_Obs_TrophicClass_Chl <-}\StringTok{ }\KeywordTok{adorn_totals}\NormalTok{(N_Obs_TrophicClass_Chl,}\StringTok{"row"}\NormalTok{)}

\CommentTok{#The number of observations are presented in the following dataframe}
\NormalTok{N_Obs_TrophicClass_Chl}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TrophicState Number_Observations
##       Eutrophic               41861
##  Hypereutrophic               14379
##     Mesotrophic               15413
##    Oligotrophic                3298
##           Total               74951
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Number of observations that fall into the four trophic state categories for }
\CommentTok{#trophic.class.secchi (using Secchi Depth)}

\NormalTok{N_Obs_TrophicClass_Secchi <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{summary}\NormalTok{(LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.secchi))}
\KeywordTok{names}\NormalTok{(N_Obs_TrophicClass_Secchi)[}\DecValTok{1}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Number_Observations"}\NormalTok{)}
\NormalTok{N_Obs_TrophicClass_Secchi <-}\StringTok{ }
\StringTok{  }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{TrophicState =} \KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_Secchi),}
\NormalTok{             N_Obs_TrophicClass_Secchi)}
\KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_Secchi) <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\NormalTok{N_Obs_TrophicClass_Secchi <-}\StringTok{ }\KeywordTok{adorn_totals}\NormalTok{(N_Obs_TrophicClass_Secchi,}\StringTok{"row"}\NormalTok{)}

\CommentTok{#The number of observations are presented in the following dataframe}
\NormalTok{N_Obs_TrophicClass_Secchi}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TrophicState Number_Observations
##    Oligotrophic               16110
##     Mesotrophic               25083
##       Eutrophic               28659
##  Hypereutrophic                5099
##           Total               74951
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Number of observations that fall into the four trophic state categories for }
\CommentTok{#trophic.class.tp (using Total phosphorus)}

\NormalTok{N_Obs_TrophicClass_tp <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{summary}\NormalTok{(LAGOStrophicComplete}\OperatorTok{$}\NormalTok{trophic.class.tp))}
\KeywordTok{names}\NormalTok{(N_Obs_TrophicClass_tp)[}\DecValTok{1}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Number_Observations"}\NormalTok{)}
\NormalTok{N_Obs_TrophicClass_tp <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{TrophicState =} \KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_tp),}
\NormalTok{                                    N_Obs_TrophicClass_tp)}
\KeywordTok{rownames}\NormalTok{(N_Obs_TrophicClass_tp) <-}\StringTok{ }\KeywordTok{c}\NormalTok{()}
\NormalTok{N_Obs_TrophicClass_tp <-}\StringTok{ }\KeywordTok{adorn_totals}\NormalTok{(N_Obs_TrophicClass_tp,}\StringTok{"row"}\NormalTok{)}

\CommentTok{#The number of observations are presented in the following dataframe}
\NormalTok{N_Obs_TrophicClass_tp}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    TrophicState Number_Observations
##    Oligotrophic               19861
##     Mesotrophic               23023
##       Eutrophic               24839
##  Hypereutrophic                7228
##           Total               74951
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  What proportion of total observations are considered eutrophic or
  hypereutrophic according to the three different metrics
  (trophic.class, trophic.class.secchi, trophic.class.tp)?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#proportion of total observations of the four trophic state categories for }
\CommentTok{#chlorophyll a concentration metric}

\NormalTok{N_Obs_TrophicClass_Chl <-}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(N_Obs_TrophicClass_Chl, }
         \DataTypeTok{Proportion =}\NormalTok{ N_Obs_TrophicClass_Chl}\OperatorTok{$}\NormalTok{Number_Observations}\OperatorTok{/}\NormalTok{N_Obs_TrophicClass_Chl[}\DecValTok{5}\NormalTok{,}\DecValTok{2}\NormalTok{])}

\CommentTok{#The proportion of observations is presented in the folowing dataframe             }
\NormalTok{N_Obs_TrophicClass_Chl}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     TrophicState Number_Observations Proportion
## 1      Eutrophic               41861 0.55851156
## 2 Hypereutrophic               14379 0.19184534
## 3    Mesotrophic               15413 0.20564102
## 4   Oligotrophic                3298 0.04400208
## 5          Total               74951 1.00000000
\end{verbatim}

\begin{quote}
20.6\% + 4.4\% = 25\% of total observations are considered eutrophic or
hypereutrophic for chlorophyll a concentration metric
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#proportion of total observations of the four trophic state categories for Secchi Depth metric}

\NormalTok{N_Obs_TrophicClass_Secchi <-}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(N_Obs_TrophicClass_Secchi, }
         \DataTypeTok{Proportion =}\NormalTok{ N_Obs_TrophicClass_Secchi}\OperatorTok{$}\NormalTok{Number_Observations}\OperatorTok{/}\NormalTok{N_Obs_TrophicClass_Secchi[}\DecValTok{5}\NormalTok{,}\DecValTok{2}\NormalTok{])}

\CommentTok{#The proportion of observations is presented in the folowing dataframe               }
\NormalTok{N_Obs_TrophicClass_Secchi}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     TrophicState Number_Observations Proportion
## 1   Oligotrophic               16110 0.21494043
## 2    Mesotrophic               25083 0.33465864
## 3      Eutrophic               28659 0.38236981
## 4 Hypereutrophic                5099 0.06803111
## 5          Total               74951 1.00000000
\end{verbatim}

\begin{quote}
38.2\% + 6.8\% = 45\% of total observations are considered eutrophic or
hypereutrophic for Secchi Depth metric
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#proportion of total observations of the four trophic state categories for Total phosphorus metric}

\NormalTok{N_Obs_TrophicClass_tp <-}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(N_Obs_TrophicClass_tp, }
         \DataTypeTok{Proportion =}\NormalTok{ N_Obs_TrophicClass_tp}\OperatorTok{$}\NormalTok{Number_Observations}\OperatorTok{/}\NormalTok{N_Obs_TrophicClass_tp[}\DecValTok{5}\NormalTok{,}\DecValTok{2}\NormalTok{])}

\CommentTok{#The proportion of observations is presented in the folowing dataframe               }
\NormalTok{N_Obs_TrophicClass_tp}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     TrophicState Number_Observations Proportion
## 1   Oligotrophic               19861 0.26498646
## 2    Mesotrophic               23023 0.30717402
## 3      Eutrophic               24839 0.33140318
## 4 Hypereutrophic                7228 0.09643634
## 5          Total               74951 1.00000000
\end{verbatim}

\begin{quote}
33.1\% + 9.6\% = 42.7\% of total observations are considered eutrophic
or hypereutrophic for Total phosphorus metric
\end{quote}

Which of these metrics is most conservative in its designation of
eutrophic conditions? Why might this be?

\begin{quote}
With 45\% of total observations considered euthrophic or hypereutrophic
compared to 25\% and 42.7\%, the Secchi Depth metric is the most
conservative. It is probably because is the least accurate estimation. I
measures water transparency to indirectly give an estimation of
concentration of suspended and dissolved material in the water, which
then is used to derive the biomass. In some cases water transparency
could be altered not only by biomass, which would lead to overestimation
of biomass by the Secchi disk metric and therefore overestimation of the
trophic state.
\end{quote}

Note: To take this further, a researcher might determine which trophic
classes are susceptible to being differently categorized by the
different metrics and whether certain metrics are prone to categorizing
trophic class as more or less eutrophic. This would entail more complex
code.

\hypertarget{nutrient-concentrations}{%
\subsection{Nutrient Concentrations}\label{nutrient-concentrations}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Create a data frame that includes the columns lagoslakeid, sampledate,
  tn, tp, state, and state\_name. Mutate this data frame to include
  sampleyear and samplemonth columns as well. Call this data frame
  LAGOSNandP.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSlocus <-}\StringTok{ }\NormalTok{LAGOSdata}\OperatorTok{$}\NormalTok{locus}
\NormalTok{LAGOSstate <-}\StringTok{ }\NormalTok{LAGOSdata}\OperatorTok{$}\NormalTok{state}
\NormalTok{LAGOSnutrient <-}\StringTok{ }\NormalTok{LAGOSdata}\OperatorTok{$}\NormalTok{epi_nutr}


\CommentTok{# Tell R to treat lakeid as a factor, not a numeric value}
\NormalTok{LAGOSlocus}\OperatorTok{$}\NormalTok{lagoslakeid <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(LAGOSlocus}\OperatorTok{$}\NormalTok{lagoslakeid)}
\NormalTok{LAGOSnutrient}\OperatorTok{$}\NormalTok{lagoslakeid <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(LAGOSnutrient}\OperatorTok{$}\NormalTok{lagoslakeid)}

\CommentTok{# Join data frames}
\NormalTok{LAGOSlocations <-}\StringTok{ }\KeywordTok{left_join}\NormalTok{(LAGOSlocus, LAGOSstate, }\DataTypeTok{by =} \StringTok{"state_zoneid"}\NormalTok{)}
\NormalTok{LAGOSNandP <-}\StringTok{ }\KeywordTok{left_join}\NormalTok{(LAGOSnutrient, LAGOSlocations, }\DataTypeTok{by =} \StringTok{"lagoslakeid"}\NormalTok{)}


\NormalTok{LAGOSNandP <-}\StringTok{ }
\StringTok{  }\NormalTok{LAGOSNandP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(lagoslakeid, sampledate, tn, tp, state, state_name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{sampleyear =} \KeywordTok{year}\NormalTok{(sampledate), }
         \DataTypeTok{samplemonth =} \KeywordTok{month}\NormalTok{(sampledate))}

\KeywordTok{head}\NormalTok{(LAGOSNandP)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   lagoslakeid sampledate tn  tp state state_name sampleyear samplemonth
## 1      126841 1985-11-05 NA 100    NY   New York       1985          11
## 2        6456 2006-06-15 NA  14    IL   Illinois       2006           6
## 3        6469 2006-06-19 NA  88    IL   Illinois       2006           6
## 4       81320 1985-11-07 NA 100    NY   New York       1985          11
## 5      122514 1988-06-23 NA 700    NY   New York       1988           6
## 6        6450 2006-08-23 NA  14    IL   Illinois       2006           8
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Create two violin plots comparing TN and TP concentrations across
  states. Include a 50th percentile line inside the violins.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSN <-}\StringTok{ }
\StringTok{  }\NormalTok{LAGOSNandP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{drop_na}\NormalTok{(tn,state)}

\NormalTok{LAGOSP <-}\StringTok{ }
\StringTok{  }\NormalTok{LAGOSNandP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{drop_na}\NormalTok{(tp,state)}


\NormalTok{LAGOSNviolin <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(LAGOSN, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{state, }\DataTypeTok{fill =}\NormalTok{state)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ tn), }\DataTypeTok{draw_quantiles =} \FloatTok{0.50}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#771155"}\NormalTok{, }\StringTok{"#AA4488"}\NormalTok{, }\StringTok{"#CC99BB"}\NormalTok{, }\StringTok{"#114477"}\NormalTok{, }\StringTok{"#4477AA"}\NormalTok{, }
                               \StringTok{"#77AADD"}\NormalTok{, }\StringTok{"#117777"}\NormalTok{, }\StringTok{"#44AAAA"}\NormalTok{, }\StringTok{"#77CCCC"}\NormalTok{, }\StringTok{"#777711"}\NormalTok{, }
                               \StringTok{"#AAAA44"}\NormalTok{, }\StringTok{"#DDDD77"}\NormalTok{, }\StringTok{"#774411"}\NormalTok{, }\StringTok{"#AA7744"}\NormalTok{, }\StringTok{"#DDAA77"}\NormalTok{, }
                               \StringTok{"#771122"}\NormalTok{, }\StringTok{"#AA4455"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"State"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{N }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Total Nitrogen per State"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(LAGOSNviolin)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSPviolin <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(LAGOSP, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{state, }\DataTypeTok{fill =}\NormalTok{ state)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ tp), }\DataTypeTok{draw_quantiles =} \FloatTok{0.50}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#771155"}\NormalTok{, }\StringTok{"#AA4488"}\NormalTok{, }\StringTok{"#CC99BB"}\NormalTok{, }\StringTok{"#114477"}\NormalTok{, }\StringTok{"#4477AA"}\NormalTok{, }
                                 \StringTok{"#77AADD"}\NormalTok{, }\StringTok{"#117777"}\NormalTok{, }\StringTok{"#44AAAA"}\NormalTok{, }\StringTok{"#77CCCC"}\NormalTok{, }\StringTok{"#777711"}\NormalTok{, }
                                 \StringTok{"#AAAA44"}\NormalTok{, }\StringTok{"#DDDD77"}\NormalTok{, }\StringTok{"#774411"}\NormalTok{, }\StringTok{"#AA7744"}\NormalTok{, }\StringTok{"#DDAA77"}\NormalTok{, }
                                 \StringTok{"#771122"}\NormalTok{, }\StringTok{"#AA4455"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"State"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{P }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Total Phosphorus per State"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(LAGOSPviolin)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-7-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# To better see the median, I scaled the y axis}

\NormalTok{LAGOSNviolin2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(LAGOSN, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{state, }\DataTypeTok{fill =}\NormalTok{state)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ tn), }\DataTypeTok{draw_quantiles =} \FloatTok{0.50}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2500}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#771155"}\NormalTok{, }\StringTok{"#AA4488"}\NormalTok{, }\StringTok{"#CC99BB"}\NormalTok{, }\StringTok{"#114477"}\NormalTok{, }\StringTok{"#4477AA"}\NormalTok{, }
                               \StringTok{"#77AADD"}\NormalTok{, }\StringTok{"#117777"}\NormalTok{, }\StringTok{"#44AAAA"}\NormalTok{, }\StringTok{"#77CCCC"}\NormalTok{, }\StringTok{"#777711"}\NormalTok{, }
                               \StringTok{"#AAAA44"}\NormalTok{, }\StringTok{"#DDDD77"}\NormalTok{, }\StringTok{"#774411"}\NormalTok{, }\StringTok{"#AA7744"}\NormalTok{, }\StringTok{"#DDAA77"}\NormalTok{, }
                               \StringTok{"#771122"}\NormalTok{, }\StringTok{"#AA4455"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"State"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{N }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Total Nitrogen per State (y axis 0 - 2500ug/L)"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(LAGOSNviolin2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-7-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSPviolin2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(LAGOSP, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{state, }\DataTypeTok{fill =}\NormalTok{ state)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ tp), }\DataTypeTok{draw_quantiles =} \FloatTok{0.50}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{125}\NormalTok{) }\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"#771155"}\NormalTok{, }\StringTok{"#AA4488"}\NormalTok{, }\StringTok{"#CC99BB"}\NormalTok{, }\StringTok{"#114477"}\NormalTok{, }\StringTok{"#4477AA"}\NormalTok{, }
                                 \StringTok{"#77AADD"}\NormalTok{, }\StringTok{"#117777"}\NormalTok{, }\StringTok{"#44AAAA"}\NormalTok{, }\StringTok{"#77CCCC"}\NormalTok{, }\StringTok{"#777711"}\NormalTok{, }
                                 \StringTok{"#AAAA44"}\NormalTok{, }\StringTok{"#DDDD77"}\NormalTok{, }\StringTok{"#774411"}\NormalTok{, }\StringTok{"#AA7744"}\NormalTok{, }\StringTok{"#DDAA77"}\NormalTok{, }
                                 \StringTok{"#771122"}\NormalTok{, }\StringTok{"#AA4455"}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"State"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{P }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Total Phosphorus per State (y axis 0 - 125ug/L)"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(LAGOSPviolin2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-7-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#To be sure about the next questions}

\NormalTok{LAGOSN_Summary <-}\StringTok{ }\NormalTok{LAGOSN }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(state_name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tN_Median =} \KeywordTok{median}\NormalTok{(tn),}
            \DataTypeTok{tN_Range =} \KeywordTok{max}\NormalTok{(tn) }\OperatorTok{-}\StringTok{ }\KeywordTok{min}\NormalTok{(tn)) }

\NormalTok{LAGOSN_Summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17 x 3
##    state_name    tN_Median tN_Range
##    <chr>             <dbl>    <dbl>
##  1 Connecticut        390     2751 
##  2 Illinois          1084.    6133 
##  3 Indiana            714     2323 
##  4 Iowa              1628.   20564.
##  5 Maine              246.    2213 
##  6 Massachusetts      532     3834 
##  7 Michigan           493    10552.
##  8 Minnesota          920    11350 
##  9 Missouri           660    11010 
## 10 New Hampshire      244      255 
## 11 New Jersey         585     2033 
## 12 New York           390    11090 
## 13 Ohio              1343    12889.
## 14 Pennsylvania       550     4750 
## 15 Rhode Island       450    10275 
## 16 Vermont            204      234 
## 17 Wisconsin          352     3893
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSP_Summary <-}\StringTok{ }\NormalTok{LAGOSP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(state_name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tP_Median =} \KeywordTok{median}\NormalTok{(tp),}
            \DataTypeTok{tP_Range =} \KeywordTok{max}\NormalTok{(tp) }\OperatorTok{-}\StringTok{ }\KeywordTok{min}\NormalTok{(tp)) }

\NormalTok{LAGOSP_Summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17 x 3
##    state_name    tP_Median tP_Range
##    <chr>             <dbl>    <dbl>
##  1 Connecticut        16.4     383 
##  2 Illinois           83.1    1217 
##  3 Indiana            34       624 
##  4 Iowa               74.4     776.
##  5 Maine              10       426 
##  6 Massachusetts      19      1200 
##  7 Michigan           10.3     590 
##  8 Minnesota          40      1200 
##  9 Missouri           34       831 
## 10 New Hampshire      10       540 
## 11 New Jersey         29       575.
## 12 New York           13       700 
## 13 Ohio               47.1     816 
## 14 Pennsylvania       20       360 
## 15 Rhode Island       14       479.
## 16 Vermont            14.9     456 
## 17 Wisconsin          20      1180
\end{verbatim}

Which states have the highest and lowest median concentrations?

\begin{quote}
TN: Highest: Iowa. Lowest: Vermont. I couldn't figure out why the Total
N plot shows a higher median for Vermont (over 250 ug/L)
\end{quote}

\begin{quote}
TP: Highest: Illinois. Lowest: New Hampshire.
\end{quote}

Which states have the highest and lowest concentration ranges?

\begin{quote}
TN: Highest: Iowa. Lowest: Vermont
\end{quote}

\begin{quote}
TP: Highest: Illinois. Lowest: Connecticut
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Create two jitter plots comparing TN and TP concentrations across
  states, with samplemonth as the color. Choose a color palette other
  than the ggplot default.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tnbystate <-}\StringTok{ }
\KeywordTok{ggplot}\NormalTok{(LAGOSN, }
       \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{as.factor}\NormalTok{(state_name), }\DataTypeTok{y =}\NormalTok{ tn, }\DataTypeTok{color =}\NormalTok{ samplemonth)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"States"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{N }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)), }\DataTypeTok{color =} \StringTok{"Month"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_viridis_c}\NormalTok{(}\DataTypeTok{option =} \StringTok{"plasma"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{))}
\KeywordTok{print}\NormalTok{(tnbystate)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tpbystate <-}\StringTok{ }
\KeywordTok{ggplot}\NormalTok{(LAGOSP, }
       \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{as.factor}\NormalTok{(state_name), }\DataTypeTok{y =}\NormalTok{ tp, }\DataTypeTok{color =}\NormalTok{ samplemonth)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"States"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{P }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)), }\DataTypeTok{color =} \StringTok{"Month"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_viridis_c}\NormalTok{(}\DataTypeTok{option =} \StringTok{"plasma"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{))}
\KeywordTok{print}\NormalTok{(tpbystate)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-8-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSN_Summary2 <-}\StringTok{ }\NormalTok{LAGOSN }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(state_name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tN_Samples =} \KeywordTok{length}\NormalTok{(tn)) }

\NormalTok{LAGOSN_Summary2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17 x 2
##    state_name    tN_Samples
##    <chr>              <int>
##  1 Connecticut          916
##  2 Illinois              46
##  3 Indiana               57
##  4 Iowa                2649
##  5 Maine                762
##  6 Massachusetts         95
##  7 Michigan             885
##  8 Minnesota           8604
##  9 Missouri           11503
## 10 New Hampshire         19
## 11 New Jersey            10
## 12 New York            8091
## 13 Ohio                1502
## 14 Pennsylvania        1044
## 15 Rhode Island        2836
## 16 Vermont                3
## 17 Wisconsin           2416
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSP_Summary2 <-}\StringTok{ }\NormalTok{LAGOSP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(state_name) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tP_Samples =} \KeywordTok{length}\NormalTok{(tp)) }

\NormalTok{LAGOSP_Summary2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17 x 2
##    state_name    tP_Samples
##    <chr>              <int>
##  1 Connecticut         1222
##  2 Illinois            2632
##  3 Indiana             1340
##  4 Iowa                2920
##  5 Maine              11987
##  6 Massachusetts        657
##  7 Michigan           10250
##  8 Minnesota          11186
##  9 Missouri           11786
## 10 New Hampshire       8164
## 11 New Jersey           516
## 12 New York           21343
## 13 Ohio                 175
## 14 Pennsylvania        1240
## 15 Rhode Island        3612
## 16 Vermont             7980
## 17 Wisconsin          45743
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSN_Summary3 <-}\StringTok{ }\NormalTok{LAGOSN }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(samplemonth) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tN_Samples =} \KeywordTok{length}\NormalTok{(tn)) }

\NormalTok{LAGOSN_Summary3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 2
##    samplemonth tN_Samples
##          <dbl>      <int>
##  1           1        191
##  2           2        267
##  3           3        194
##  4           4       1507
##  5           5       5173
##  6           6       8014
##  7           7       9880
##  8           8       8451
##  9           9       4344
## 10          10       2803
## 11          11        537
## 12          12         77
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSP_Summary3 <-}\StringTok{ }\NormalTok{LAGOSP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(samplemonth) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tP_Samples =} \KeywordTok{length}\NormalTok{(tp)) }

\NormalTok{LAGOSP_Summary3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 2
##    samplemonth tP_Samples
##          <dbl>      <int>
##  1           1       1279
##  2           2       2215
##  3           3       1821
##  4           4       8790
##  5           5      14221
##  6           6      22637
##  7           7      30410
##  8           8      31606
##  9           9      16094
## 10          10      10250
## 11          11       2826
## 12          12        604
\end{verbatim}

Which states have the most samples? How might this have impacted total
ranges from \#9?

\begin{quote}
TN: Missouri 11.503, Minnesota 8604, and New York 8.091
\end{quote}

\begin{quote}
TP: Wisconsin 45.743 and New York 21.343
\end{quote}

\begin{quote}
Number of samples totally could impact the total ranges of samples
because a higher number of samples probably means that the samples were
taken at different seasons, times, environmental conditions, and for a
longer period of time (which makes more probable the presence of
outliers) than data sets with fewer samples.
\end{quote}

Which months are sampled most extensively? Does this differ among
states?

\begin{quote}
TN: July, August, and June in decreasing order. According to the jitter
plot, it differ among states. For example it can be seen that Iowa has
more red/pink/purple values (summer months) and New York, Maine, and
Rhode Island have a greater concentrations of yellow/orange values (fall
months).
\end{quote}

\begin{quote}
TP: August, July, and June in decreasing order. According to the jitter
plot, it differ among states. For example it can be seen that Michigan,
Vermont and Wisconsin have more blue/purple values (winter months) than
the rest of the states. New York, Massachusetts, and Rhode Island have a
greater concentrations of yellow/orange values (fall months).
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Create two jitter plots comparing TN and TP concentrations across
  states, with sampleyear as the color. Choose a color palette other
  than the ggplot default.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tnbystate <-}\StringTok{ }
\KeywordTok{ggplot}\NormalTok{(LAGOSN, }
       \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{as.factor}\NormalTok{(state_name), }\DataTypeTok{y =}\NormalTok{ tn, }\DataTypeTok{color =}\NormalTok{ sampleyear)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"States"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{N }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)), }\DataTypeTok{color =} \StringTok{"Year"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_viridis_c}\NormalTok{(}\DataTypeTok{option =} \StringTok{"plasma"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{))}
\KeywordTok{print}\NormalTok{(tnbystate)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tpbystate <-}\StringTok{ }
\KeywordTok{ggplot}\NormalTok{(LAGOSP, }
       \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{as.factor}\NormalTok{(state_name), }\DataTypeTok{y =}\NormalTok{ tp, }\DataTypeTok{color =}\NormalTok{ sampleyear)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_jitter}\NormalTok{(}\DataTypeTok{alpha =} \FloatTok{0.2}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{"States"}\NormalTok{, }\DataTypeTok{y =} \KeywordTok{expression}\NormalTok{(Total }\OperatorTok{~}\StringTok{ }\NormalTok{P }\OperatorTok{~}\StringTok{ }\NormalTok{(mu}\OperatorTok{*}\NormalTok{g }\OperatorTok{/}\StringTok{ }\NormalTok{L)), }\DataTypeTok{color =} \StringTok{"Year"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_viridis_c}\NormalTok{(}\DataTypeTok{option =} \StringTok{"plasma"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{90}\NormalTok{))}
\KeywordTok{print}\NormalTok{(tpbystate)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A05_Raby_LakeWQ_files/figure-latex/unnamed-chunk-9-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSN_Summary4 <-}\StringTok{ }\NormalTok{LAGOSN }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(sampleyear) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tN_Samples =} \KeywordTok{length}\NormalTok{(tn)) }

\KeywordTok{tail}\NormalTok{(LAGOSN_Summary4, }\DataTypeTok{n=}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 2
##    sampleyear tN_Samples
##         <dbl>      <int>
##  1       1999       1242
##  2       2000       1119
##  3       2001       1863
##  4       2002       2253
##  5       2003       2437
##  6       2004       2399
##  7       2005       2877
##  8       2006       3052
##  9       2007       3336
## 10       2008       3120
## 11       2009       3594
## 12       2010       3103
## 13       2011       1927
## 14       2012        775
## 15       2013        313
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LAGOSP_Summary4 <-}\StringTok{ }\NormalTok{LAGOSP }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(sampleyear) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{tP_Samples =} \KeywordTok{length}\NormalTok{(tp)) }

\KeywordTok{tail}\NormalTok{(LAGOSP_Summary4, }\DataTypeTok{n=}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 2
##    sampleyear tP_Samples
##         <dbl>      <int>
##  1       1999       4582
##  2       2000       4698
##  3       2001       5949
##  4       2002       5261
##  5       2003       5452
##  6       2004       6156
##  7       2005       6394
##  8       2006       6617
##  9       2007       6451
## 10       2008       6325
## 11       2009       7071
## 12       2010       6913
## 13       2011       5414
## 14       2012       2876
## 15       2013       2624
\end{verbatim}

Which years are sampled most extensively? Does this differ among states?

\begin{quote}
TN: From 2005 to 2010. According to the jitter plot it does not differ
much among states. They all seem to have greater concentration of yellow
values. Some states such as Wisconsin, Connecticut, and Rhode Island
have values more orange, pink, or even purple, meaning that they have
more concentration of values from the 1990s, 1980s, and 1970s.
\end{quote}

\begin{quote}
TP: From 2004 to 2010. According to the jitter plot it does differ among
states, at least more that the TN plot. There are more ``yellow'' states
(2000s) such as Iowa or Ohio and more ``red/orange'' states (1990s) like
Minnesota or Maine.
\end{quote}

\hypertarget{reflection}{%
\subsection{Reflection}\label{reflection}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  What are 2-3 conclusions or summary points about lake water quality
  you learned through your analysis?
\end{enumerate}

\begin{quote}
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The trophic state can be calculated using chlorophyll a concentration,
  Secchi disk transparency, and Total phosphorus (TP).
\item
  The results obtained by each one of the variables can be different.
  chlorophyll a concentration would probably be the most accurate, but
  Secchi disk is an affordable measurement that can be used as a easy
  first estimation of the trophic state.
\item
  The number of measurements and values of TP and TN can vary
  considerably between states
\end{enumerate}
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  What data, visualizations, and/or models supported your conclusions
  from 12?
\end{enumerate}

\begin{quote}
For 1. and 2. Calculation of trophic state using the three variables.
For 3. all the jitter and violin plots.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Did hands-on data analysis impact your learning about water quality
  relative to a theory-based lesson? If so, how?
\end{enumerate}

\begin{quote}
It did. I like how hands-on makes you have doubts that you have to do
research by yourself to solve them, compared to a theory-based lesson
were the professor gives you all the answers in class.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  How did the real-world data compare with your expectations from
  theory?
\end{enumerate}

\begin{quote}
I didn't have much previous knowledge about the topic so I didn't know
what to expect. The LAGOS data looks amazing.
\end{quote}


\end{document}
